kind = "DojoContract"
class_hash = "0x666e80490bf0ce1e1fd685b3625d35343947ed8fde4704fd64f7ba46ad4c487"
original_class_hash = "0x666e80490bf0ce1e1fd685b3625d35343947ed8fde4704fd64f7ba46ad4c487"
base_class_hash = "0x0"
abi = "manifests/release/base/abis/contracts/dojo_examples-actions-40b6994c.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples-actions"
manifest_name = "dojo_examples-actions-40b6994c"
