kind = "DojoContract"
class_hash = "0x7b59e8f1039dd99e39af7695bbbd5bcc4ffd7852f54576fe4acf89590298c01"
original_class_hash = "0x7b59e8f1039dd99e39af7695bbbd5bcc4ffd7852f54576fe4acf89590298c01"
base_class_hash = "0x0"
abi = "manifests/release/base/abis/contracts/dojo_examples-actions-40b6994c.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples-actions"
manifest_name = "dojo_examples-actions-40b6994c"
