[package]
edition.workspace = true
license-file.workspace = true
license.workspace = true
name = "torii-libp2p"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures.workspace = true
libp2p = { git = "https://github.com/libp2p/rust-libp2p", features = [ "ed25519", "gossipsub", "identify", "macros", "mdns", "noise", "ping", "quic", "relay", "tcp", "tokio", "yamux" ] }
libp2p-webrtc = { git = "https://github.com/libp2p/rust-libp2p", features = [ "tokio" ] }
rand = "0.8.5"
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing.workspace = true
async-trait = "0.1.77"
regex = "1.10.3"
