kind = "DojoContract"
class_hash = "0x1e25819012944715e33045da9b9f1bced52553412935816b3886cffe5ce0d90"
original_class_hash = "0x1e25819012944715e33045da9b9f1bced52553412935816b3886cffe5ce0d90"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_examples-actions-49cbe40e.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples:actions"
manifest_name = "dojo_examples-actions-49cbe40e"
