kind = "DojoContract"
class_hash = "0x112caad1aed1e3d21fc70eb118db9ff75632f1e3f6c2f387d116fcb6e1eee4"
original_class_hash = "0x112caad1aed1e3d21fc70eb118db9ff75632f1e3f6c2f387d116fcb6e1eee4"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_examples-others-61de2c18.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples-others"
manifest_name = "dojo_examples-others-61de2c18"
