kind = "DojoContract"
class_hash = "0x6910afc015688ae45ca113e39de97cf0727115bbdcf32b9bd9852d51e4e990c"
original_class_hash = "0x6910afc015688ae45ca113e39de97cf0727115bbdcf32b9bd9852d51e4e990c"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_examples_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_examples::actions::actions"
