kind = "DojoContract"
class_hash = "0x19b523370103f906717f8fb84cc420631941e7cbbdc4564f95f4a73244e4805"
original_class_hash = "0x19b523370103f906717f8fb84cc420631941e7cbbdc4564f95f4a73244e4805"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_examples_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_examples::actions::actions"
