kind = "DojoModel"
class_hash = "0x3ccc02f75eb62a2c3b1cacd1d5df433c5275868073288ff2e5b976674a2d414"
original_class_hash = "0x3ccc02f75eb62a2c3b1cacd1d5df433c5275868073288ff2e5b976674a2d414"
abi = "manifests/dev/abis/base/models/dojo_examples_models_message.json"
name = "dojo_examples::models::message"

[[members]]
name = "identity"
type = "ContractAddress"
key = true

[[members]]
name = "message"
type = "ByteArray"
key = false

[[members]]
name = "channel"
type = "felt252"
key = false
