kind = "DojoModel"
class_hash = "0x66a806d59e69873946a5b06e0e3df94c2f9cb139d8cc32f73e4f9ebc0ff885"
original_class_hash = "0x66a806d59e69873946a5b06e0e3df94c2f9cb139d8cc32f73e4f9ebc0ff885"
abi = "manifests/dev/abis/base/models/dojo_examples-ServerProfile-71e0f153.json"
tag = "dojo_examples:ServerProfile"
manifest_name = "dojo_examples-ServerProfile-71e0f153"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "server_id"
type = "u32"
key = true

[[members]]
name = "name"
type = "ByteArray"
key = false
