[world]
kind = "Contract"
class_hash = "0xfab8f0fbd397ada7cdebd9f6399fb9694a76fa55646c9cfcc41b813a1b8324"
address = "0x4156b846546b27dc63788beec27b8b5a76b7732fae5f32aa963326a20ee3abf"
transaction_hash = "0x7aac53833c28600ec4d2e87ceaf22ee8152ac0e4f26964a685e36cd7b9b9b49"
block_number = 3
seed = "dojo_examples"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x5720cdb134fd7413a3e7335fb29afb9db75ab43b743f2f3511d0aadea9734f2"
class_hash = "0x3eae5e5494ce9058762a4ff585e2c58eabe37dad9a33d8bddd9667e4e54afe5"
abi = "abis/deployments/KATANA/contracts/actions.json"
reads = [
    "Moves",
    "Position",
]
writes = []
computed = []
name = "dojo_examples::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x52659850f9939482810d9f6b468b91dc99e0b7fa42c2016cf12833ec06ce911"
name = "dojo_examples::actions::actions::moved"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x511fbd833938f5c4b743eea1e67605a125d7ff60e8a09e8dc227ad2fb59ca54"
name = "dojo_examples::models::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xb33ae053213ccb2a57967ffc4411901f3efab24781ca867adcd0b90f2fece5"
name = "dojo_examples::models::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false
