[package]
name = "client-bin"
edition.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
torii-libp2p = { version = "0.5.1-alpha.0", path = "../libp2p" }
