[package]
name = "client-bin"
edition.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures.workspace = true
tokio.workspace = true
serde_json.workspace = true
torii-client = { version = "0.5.1-alpha.0", path = "../client" }
torii-libp2p = { version = "0.5.1-alpha.0", path = "../libp2p" }
libp2p = { version = "0.53.2", features = ["gossipsub"] }
