kind = "DojoContract"
class_hash = "0x2a76f77a828c13813820157716fc9af189ca51a5be6f40e5168392345ad22b7"
abi = "abis/base/contracts/actions.json"
reads = []
writes = []
computed = []
name = "dojo_examples::actions::actions"
