kind = "DojoContract"
class_hash = "0x484cfecf0899a34820e62baf5f7dd1e17c1bcc08f8e595ff394ea16f9a5becd"
abi = "abis/base/contracts/records.json"
reads = []
writes = []
computed = []
name = "types_test::contracts::records"
